# Generated by Django 4.0.1 on 2023-02-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('artist_url', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=50)),
                ('album_url', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album_cover', models.CharField(max_length=100)),
            ],
        ),
    ]
