# Generated by Django 4.0.1 on 2023-02-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_artist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='price',
        ),
    ]
