# Generated by Django 4.0.1 on 2023-02-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_artist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_url',
        ),
    ]
